services:
  - type: web
    name: market_oyle
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn devmarketer_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: market_oyle_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: market_oyle_db
    databaseName: market_oyle
    user: market_oyle_user