services:
  - type: web
    name: devmarketer
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn devmarketer_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: devmarketer_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: devmarketer_db
    databaseName: devmarketer
    user: devmarketer